name: CI/CD Deploy to EC2

on:
  push:
    branches:
      - main # Deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private_key.pem
          chmod 600 ~/.ssh/private_key.pem
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync files to EC2
        run: |
          rsync -avz -e "ssh -i ~/.ssh/private_key.pem -o StrictHostKeyChecking=no" ./ ${EC2_USER}@${EC2_HOST}:/home/${EC2_USER}/app

      - name: Set up environment file
        run: |
          ssh -tt -i ~/.ssh/private_key.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << 'EOF'
            echo "$ENV_FILE_CONTENT" | sudo tee /etc/app.env > /dev/null 
            sudo chmod 600 /etc/app.env
            sudo chown ${EC2_USER}:${EC2_USER} /etc/app.env
          EOF
        env:
          ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}

      - name: Install dependencies and build app
        run: |
          ssh -tt -i ~/.ssh/private_key.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << 'EOF'
            cd /home/${EC2_USER}/app
            source /etc/app.env
            npm install          # Installs dependencies
            npm run build        # Builds the project
          EOF

      - name: Restart application on EC2
        run: |
          ssh -tt -i ~/.ssh/private_key.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << 'EOF'
            source /etc/app.env
            sudo systemctl daemon-reload
            sudo systemctl restart myapp.service
          EOF
